# Generated by Django 5.2.8 on 2025-11-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='cpf',
            new_name='matricula',
        ),
    ]
