# Generated by Django 5.2.8 on 2025-11-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_rename_cpf_colaborador_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
