# Generated by Django 5.2.8 on 2025-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_cargo_colaborador_data_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
