# Generated by Django 5.2.8 on 2025-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='ca',
            field=models.CharField(default=1, max_length=50, verbose_name='C.A.'),
            preserve_default=False,
        ),
    ]
