# Generated by Django 5.2.8 on 2025-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_epi_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
